### PR TITLE
Release 2.4.4

### PR DESCRIPTION
**Pull request by dnlbln**

### CODE REVIEW

**Review by fromdusttilldawn — COMMENTED** [review]
There still seems to be a problem with multiple regions in one annotation on some basemaps:
Deutschland - Bundesländer (geografisch): https://q.st-staging.nzz.ch/editor/choropleth/60c9328b75d7c8e4ef1ccb6c73c91b6d
Deutschland - Landkreise: https://q.st-staging.nzz.ch/editor/choropleth/60c9328b75d7c8e4ef1ccb6c73c92738

**Comment by dnlbln** [comment]
> There still seems to be a problem with multiple regions in one annotation on some basemaps: Deutschland - Bundesländer (geografisch): https://q.st-staging.nzz.ch/editor/choropleth/60c9328b75d7c8e4ef1ccb6c73c91b6d Deutschland - Landkreise: https://q.st-staging.nzz.ch/editor/choropleth/60c9328b75d7c8e4ef1ccb6c73c92738

Fix is pushed. Problem was that the german GEOJSON does not contain ids for the regions so the clustering would fail. I have added a fallback to use the name when id is missing.

Also I have added two fixtures with annotation tests. If you have more specific test regions you want to add, I suggest making some and prefixing it with FIXTURE as I did with mine so we can always fall back to it to test:
Screenshot 2022-04-28 at 12 08 38

**Comment by fromdusttilldawn** [comment]
World map crashes :(
Welt - Länder: https://q.st-staging.nzz.ch/item/f8a4848fef60ff36af8cea1bef4c9b2d

**Comment by dnlbln** [comment]
> World map crashes :( Welt - Länder: https://q.st-staging.nzz.ch/item/f8a4848fef60ff36af8cea1bef4c9b2d

Found the problem. Fix is pushed!

**Review by fromdusttilldawn — APPROVED** [review]
👏

**Pull request merged**
